### ISSUE TITLE
More information - How to calculate meanFragmentLength

### ISSUE THREAD

**Issue by sagarutturkar** [AAlhendi1707/countToFPKM#1]
Hello,

Thank you for providing this as a package and will help to streamline the calculations across users. I have seen some students performing wrong calculation.

1. Can you please include the example data files (counts, annotations, sample_metric)? 

2. `Picard CollectInsertSizeMetrics` has columns:
```
MEDIAN_INSERT_SIZE
MODE_INSERT_SIZE
MEDIAN_ABSOLUTE_DEVIATION
MIN_INSERT_SIZE
MAX_INSERT_SIZE
MEAN_INSERT_SIZE
....and so on
```
For the `meanFragmentLength` are you referring to **MEAN_INSERT_SIZE** column? Just need to confirm since there could be [different interpretations](http://thegenomefactory.blogspot.com/2013/08/paired-end-read-confusion-library.html) for fragment/insert.

Thank you.

**Comment by AAlhendi1707** [comment]
Hi there,

I have added an example RNA-seq dataset to the package that can be used to validate your work. See 
[README.md](https://github.com/AAlhendi1707/countToFPKM/blob/master/README.md) for the usage example.

The fragment length is determined by your sequencing protocol. It’s more or less the distance between the two paired reads (including the read lengths, minus any overlap). For a typical long RNA-seq library prep it’s often in the order of 300–600 bp. You can run Picard’s CollectInsertSizeMetrics tool on your aligned BAM files to find the mean fragment length.

<img style="margin:1rem;" width="50%" src="https://www.frontiersin.org/files/Articles/77572/fgene-05-00005-HTML/image_m/fgene-05-00005-g001.jpg" />
Also read <a href="https://doi.org/10.3389/fgene.2014.00005"> this paper </a> for more info about the fragment lenght calculation.

**Comment by sagarutturkar** [comment]
Thank you! This is helpful!!

**Comment by JonDo352** [comment]
Hi AAlhendi1707,

I have searched this problem over and over, and I keep getting routed back to this page. How does one convert from MEAN_INSERT_SIZE to meanFragmentLength? I have seen your posted example, but I am still having trouble understanding this. Any help would be appreciated.

Thank you.

**Comment by Counts-Xin** [comment]
> Thank you! This is helpful!!

so，that means mean INSERT_SIZE plus 2*adapter?

**Comment by sherry308** [comment]
Can you please explain in detail how to get fragments size from Piccard. If it it insert size + adapter length, Where I will get information related rot adapter length?

**Comment by Sanataniitb** [comment]
The [CollectInsertSizeMetrics(Picard)] tool requires input BAM/SAM file for finding out the mean fragment length. Where as I have only the count matrix file. Is there any way to find the mean fragment length if I only have the count matrix file.

**Comment by Nairobi-2020** [comment]
https://www.biostars.org/p/83901/
for whole transcriptome, this thread is helpful.

**Comment by Nairobi-2020** [comment]
I do not think we need to consider insertion size, etc. It evens out in large number.
Just the panel that selects regions, and how long of the panel is on the gene.

**Comment by camilla0801** [comment]
Hi, I don't understand the output of Picard. How do I get meanFragmentLengthfrom MEAN_INSERT_SIZE? in my case it's a number and it does not make any sense.
