### ISSUE TITLE
Using The [CollectInsertSizeMetrics(Picard)] tool 

### ISSUE THREAD

**Issue by Sanataniitb** [AAlhendi1707/countToFPKM#12]
This tool requires input BAM/SAM file for finding out the mean fragment length. Where as I have only the count matrix file. Is there any way to find the mean fragment length if I only have the count matrix file.

**Comment by xiaowenchenjax** [comment]
I have the same issues. look forward to your reply. thanks.

**Comment by AAlhendi1707** [comment]
Hi both,
You need average fragment lenght to convert count matrix to FPKM. If you are using read count data from publicly available datasets such as https://www.ebi.ac.uk/arrayexpress, or GEO expression datasets, then the insert size is mentioned in the **metadata** section of the experiment. Hope it helps!
