### ISSUE TITLE
How to calculate meanFragmentLength

### ISSUE THREAD

**Issue by excel9** [AAlhendi1707/countToFPKM#4]
Hello,

I am very new to bioinformatics and I am trying to use your Rcodes to calculate FPKM from a paired-end RNA seq count file. I am stuck at the use of CollectInsertSizeMetrics(Picard) tool to calculate meanFRagmentLength. I was wondering if you could provide a step-by-step guidance to using that tool. The rest of your instructions are very easy to understand from a standpoint of biologist who is very new to bioinformatics. 

Thank you for your help!

**Comment by AAlhendi1707** [comment]
Hi there,

Please find the answer in the below link
[https://github.com/AAlhendi1707/countToFPKM/issues/1
](https://github.com/AAlhendi1707/countToFPKM/issues/1
)
kind regards

**Comment by mholtz2** [comment]
The issue you link to still does not give instructions on the inputs for CollectInsertSizeMetrics. I am having trouble understanding how to produce the appropriate input files. Please provide code or more clear instructions for this that a beginner can follow.
