### ISSUE TITLE
FPKM was not computed for certain genes in the count file.

### ISSUE THREAD

**Issue by excel92021** [AAlhendi1707/countToFPKM#8]
Hi

I used your code for paired-end data and calculated FPKM of genes. However, if my count file say had 5 genes and 30 samples, the FPKM was returned for only 2 genes, 30 samples. For all the genes, there were a few samples with 0 counts. So I am not able to understand why FPKM for certain genes were not computed.

Thanks!

**Comment by AAlhendi1707** [comment]
Try to use the latest version from Github

## latest version, install countToFPKM from GitHub
if(!require(devtools)) install.packages("devtools")
devtools::install_github("AAlhendi1707/countToFPKM", build_vignettes = TRUE)
